name: Release Java App

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build JAR with Maven
      run: mvn clean install

    - name: Find JAR Name
      id: findjar
      run: |
        JAR_PATH=$(ls target/*.jar | head -n 1)
        echo "JAR_NAME=$JAR_PATH" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Tag Docker Image
      run: |
        IMAGE=${{ secrets.DOCKER_USERNAME }}/java-ci-app
        TAG=${{ github.ref_name }}
        docker build --build-arg JAR_NAME=$JAR_NAME -t $IMAGE:$TAG .
        docker tag $IMAGE:$TAG $IMAGE:latest

    - name: Push Docker Image to Docker Hub
      run: |
        IMAGE=${{ secrets.DOCKER_USERNAME }}/java-ci-app
        TAG=${{ github.ref_name }}
        docker push $IMAGE:$TAG
        docker push $IMAGE:latest